version: '3'

services:
  app:
    image: deetoo/app:bdmlr-${TAG}
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - deetoo-overlay
networks:
  deetoo-overlay:
    external:
      name: deetoo-overlay