query Article($where: JSON) {
    articles(limit: 1, where: $where) {
        id
        Identifier
        Title
        Description
        Content
        Active
        createdAt
        Media {
            id
            provider
            hash
            url
            name
        }
        categories {
            id
            Identifier
            Name
            Description
            Active
        }
        person {
            id
            Identifier
            First_Name
            Last_Name
            Email
            Active
        }
    }
}
